name: my_quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  http: ^1.2.2 # Or the latest version of the package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - lib/assets/category_banner.jpg
    - lib/assets/sound.mp3
